#!/bin/bash

# Script para actualizar cabeceras de GABpbx a tus datos de 7Kas

# Define tu nueva cabecera aquí:
read -r -d '' NEW_HEADER << 'EOF'
/*
 * GABpbx -- An open source telephony toolkit.
 *
 * Copyright (C) 1999 - 2025, 7Kas Servicios de Internet SL
 *
 * Germán Luis Aracil Boned <garacil@7kas.com>
 *
 * See http://www.gabpbx.org for more information about
 * the GABpbx project. Please do not directly contact
 * any of the maintainers of this project for assistance;
 * the project provides a web site, mailing lists and IRC
 * channels for your use.
 *
 * This program is free software, distributed under the terms of
 * the GNU General Public License Version 2. See the LICENSE file
 * at the top of the source tree.
 */
EOF

# Opcional: nueva cabecera de Doxygen también
read -r -d '' NEW_DOXYGEN << 'EOF'
/*! 
 * \mainpage GABpbx -- The Open Source Telephony Project
 *
 * \par Welcome
 *
 * This documentation created by the Doxygen project clearly explains the
 * internals of the GABpbx software. This documentation contains basic
 * examples, developer documentation, support information, and information
 * for upgrading.
 *
 * \section community Community
 * GABpbx is a big project and has a busy community. Look at the
 * resources for questions and stick around to help answer questions.
 * \li \ref gabpbx_community_resources
 *
 * \par Developer Documentation for GABpbx
 *
 * This is the main developer documentation for GABpbx. It is
 * generated by running "make progdocs" from the GABpbx source tree.
 *
 * In addition to the information available on the GABpbx source code,
 * please see the appendices for information on coding guidelines,
 * release management, commit policies, and more.
 *
 * \arg \ref GABpbxArchitecture
 *
 * \par Additional documentation
 * \arg \ref Licensing
 * \arg \ref DevDoc
 * \arg \ref configuration_file
 * \arg \ref channel_drivers
 * \arg \ref applications
 *
 * \section copyright Copyright and Author
 *
 * Copyright (C) 1999 - 2025, 7Kas Servicios de Internet SL.
 *
 * GABpbx is a trademark of 7Kas Servicios de Internet SL.
 *
 * \author Germán Luis Aracil Boned <garacil@7kas.com>
 *
 * See http://www.gabpbx.org for more information about
 * the GABpbx project. Please do not directly contact
 * any of the maintainers of this project for assistance;
 * the project provides a web site, mailing lists, and IRC
 * channels for your use.
 */
EOF

# Carpeta raíz donde está tu código
SOURCE_DIR="."

# Extensiones a procesar
EXTENSIONS=("*.c" "*.h" "*.cpp" "*.cc" "*.hh")

# Función para reemplazar la cabecera
replace_header() {
    local file="$1"

    # Hacemos backup del fichero original
    cp "$file" "$file.bak"

    # Elimina la cabecera vieja (hasta la primera línea vacía tras el primer bloque comentario)
    awk '
        BEGIN { skip = 0 }
        /^\s*\/\*/ { skip = 1 }
        skip && /^\s*\*\/$/ { skip = 0; next }
        !skip { print }
    ' "$file.bak" > "$file.tmp"

    # Ahora escribe la nueva cabecera + contenido
    {
        echo "$NEW_HEADER"
        echo
        cat "$file.tmp"
    } > "$file"

    rm "$file.tmp"
    echo "Actualizado: $file"
}

# Recorremos los ficheros
for ext in "${EXTENSIONS[@]}"; do
    find "$SOURCE_DIR" -type f -name "$ext" | while read -r file; do
        replace_header "$file"
    done
done

# Opcionalmente podrías hacer algo similar con archivos Doxygen (.dox) si tienes.

